services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d notes_db || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    image: backend-azure:v1            # using the image you already built
    environment:
      PORT: "3001"
      DATABASE_URL: "postgresql://postgres:password@db:5432/notes_db"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3001"
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend             # compose file is in backend/, so go up one
      args:
        REACT_APP_API_URL: http://localhost:3001
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  dbdata:
